services:
  # Servicio para la aplicación en Go
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydatabase
      - DB_PORT=5432
    networks:
      - mynetwork

  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d # Aquí se montan los scripts SQL
    networks:
      - mynetwork

# Volumen para persistir los datos de PostgreSQL
volumes:
  postgres_data:

# Red para conectar los servicios
networks:
  mynetwork: