services:
  db:
    image: postgres:16-alpine
    ports:
      - "5633:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  db_images:
    image: postgres:16-alpine
    ports:
      - "5635:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: images_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - images_postgres_data:/var/lib/postgresql/data
      # Usar el mismo directorio de inicialización que db
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  db_text:
    image: postgres:16-alpine
    ports:
      - "5634:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: text_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - text_postgres_data:/var/lib/postgresql/data
      # Usar el mismo directorio de inicialización que db
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      db_images:
        condition: service_healthy
      db_text:
        condition: service_healthy
    environment:
      # DB DATA
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=email@email.com
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydatabase
      - DB_PORT=5432
      - DB_TIMEZONE=America/Caracas
      # DB IMAGENES
      - DB_HOST_IMAGE=db_images
      - DB_USER_IMAGE=postgres
      - DB_PASSWORD_IMAGE=postgres
      - DB_NAME_IMAGE=images_database
      - DB_PORT_IMAGE=5432
      - DB_TIMEZONE_IMAGE=America/Caracas
      # DB TEXT
      - DB_HOST_TEXT=db_text
      - DB_USER_TEXT=postgres
      - DB_PASSWORD_TEXT=postgres
      - DB_NAME_TEXT=text_database
      - DB_PORT_TEXT=5432
      - DB_TIMEZONE_TEXT=America/Caracas
      - DEVELOPMENT=true
      - AUTOMIGRATE=true
      # - DEVELOPMENT=true
      # - AUTOMIGRATE=true
    networks:
      - mynetwork

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db
  #     - db_images
  #   networks:
  #     - mynetwork

volumes:
  postgres_data:
  images_postgres_data:
  text_postgres_data:

networks:
  mynetwork: