version: '3.8'

services:
  # Servicio para la aplicación en Go
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydatabase
      - DB_PORT=5432
      - DB_TIMEZONE=America/Caracas
      - DEVELOPMENT=false
      - AUTOMIGRATE=false
    networks:
      - mynetwork

  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:16-alpine
    ports:
      - "5633:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  # Servicio para pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynetwork

# Volumen para persistir los datos de PostgreSQL
volumes:
  postgres_data:

# Red para conectar los servicios
networks:
  mynetwork: